on: 
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
    
name: Test and publish

env:
  CC_BINARY_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  IMAGE_NAME: ecadlabs/signatory

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: Setup Code Climate test-reporter
        run: |
          curl -L "$CC_BINARY_URL" > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Run tests
        run: |
          export GIT_COMMIT_SHA='${{ github.sha }}'
          export GIT_BRANCH="$(echo '${{ github.ref }}' | sed -E -e 's/.*\/(.*)/\1/')"
          export CC_TEST_REPORTER_ID='${{ secrets.CC_TEST_REPORTER_ID }}'

          ./cc-test-reporter before-build

          echo "Running tests..."
          go test -coverprofile c.out ./...

          mod="$(cat go.mod | awk '/^module/ {print $2}')"

          if [[ ! -z "$CC_TEST_REPORTER_ID" ]]; then
            echo "Generating coverage report..."
            ./cc-test-reporter after-build -p "${mod}/" -t gocov
          fi
  publish:
    name: Publish
    #    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
